name: Deploy to Vercel

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Configure npm for JFrog Artifactory
        run: echo "//useast.jfrog.lexisnexisrisk.com/artifactory/api/npm/riskn-npm-release-virtual/:_authToken=${{ secrets.JFROG_API_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build project
        run: |
          npx vercel pull --token ${{ secrets.VERCEL_TOKEN }} --yes
          npx vercel build

      - name: Move build files to root
        run: |
          mv dist/css-variable-extractor/browser/* dist/css-variable-extractor/
          rm -r dist/css-variable-extractor/browser

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "deploy --prebuilt"

      - name: Promote to production (if build is successful)
        run: |
          # Get the latest deployment URL
          DEPLOYMENT_URL=$(npx vercel --token ${{ secrets.VERCEL_TOKEN }} --org ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }} ls --prod --json | jq -r '.[0].url')

          # Promote the build to production
          curl -X POST https://api.vercel.com/v1/now/deployments/${{ secrets.VERCEL_DEPLOYMENT_ID }}/promote \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -d '{"target": "production"}'
