name: Deploy to Vercel (and Azure Web App)

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Configure npm for JFrog Artifactory
        run: echo "//useast.jfrog.lexisnexisrisk.com/artifactory/api/npm/riskn-npm-release-virtual/:_authToken=${{ secrets.JFROG_API_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Bump version and generate changelog
        run: npx standard-version --release-as minor

      - name: Build project
        run: npm run build --omit=dev

      - name: Move build files to root
        run: |
          mv dist/css-variable-extractor/browser/* dist/css-variable-extractor/
          rm -r dist/css-variable-extractor/browser

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
