name: Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      - name: Configure npm for JFrog Artifactory
        run: echo "//useast.jfrog.lexisnexisrisk.com/artifactory/api/npm/riskn-npm-release-virtual/:_authToken=${{ secrets.JFROG_API_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Bump version and generate changelog
        run: npx standard-version --release-as minor

      - name: Build project
        run: npm run build --omit=dev

      - name: Debug Build Directory
        run: ls -la dist/

      - name: Archive build output
        run: zip -r build.zip dist/css-variable-extractor/*

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "css-variables-extractor"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build.zip
