name: Deploy to Vercel

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_NAME: ${{ secrets.USER_NAME }}
  JFROG_API_TOKEN: ${{ secrets.JFROG_API_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Cache Node.js dependencies
      - name: Cache Node.js Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 3: Set up Node.js
      - name: Set up Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 4: Configure Git
      - name: Configure Git User
        run: |
          git config --global user.email $USER_EMAIL
          git config --global user.name $USER_NAME

      # Step 5: Configure npm for JFrog Artifactory
      - name: Configure npm for JFrog
        run: echo "//useast.jfrog.lexisnexisrisk.com/artifactory/api/npm/riskn-npm-release-virtual/:_authToken=${{ env.JFROG_API_TOKEN }} >> ~/.npmrc

      # Step 6: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 7: Run Linting
      - name: Run ESLint Checks
        run: npm run lint

      # Step 8: Run Unit Tests
      - name: Run Tests
        run: npm run test

      # Step 9: Build the project
      - name: Build Project for Deployment
        run: |
          npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          npx vercel build --prod --token=$VERCEL_TOKEN

      # Step 10: Move build files to root (if required by your project structure)
      - name: Move Build Files
        run: |
          mv dist/css-variable-extractor/browser/* dist/css-variable-extractor/
          rm -r dist/css-variable-extractor/browser

      # Step 11: Deploy to Vercel
      - name: Deploy to Vercel
        id: deploy
        run: |
          echo "Deploying project to Vercel..."
          DEPLOY_OUTPUT=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN)
          echo "Deployment output: $DEPLOY_OUTPUT"

          # Extract deployment URL
          DEPLOYMENT_URL=$(echo "$DEPLOY_OUTPUT" | grep -oE "https://[a-zA-Z0-9.-]+\.vercel\.app")
          if [ -z "$DEPLOYMENT_URL" ]; then
            echo "Error: Deployment URL could not be extracted."
            exit 1
          fi
          echo "Deployment URL: $DEPLOYMENT_URL"
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_ENV

      # Step 12: Extract Deployment ID from URL
      - name: Extract Deployment ID
        run: |
          echo "Extracting Deployment ID from URL..."
          DEPLOYMENT_ID=$(echo "${{ env.deployment_url }}" | awk -F '/' '{print $NF}')
          if [ -z "$DEPLOYMENT_ID" ]; then
            echo "Error: Deployment ID could not be extracted."
            exit 1
          fi
          echo "Deployment ID: $DEPLOYMENT_ID"
          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_ENV

      # Step 13: Promote Deployment
      - name: Promote Deployment
        run: |
          echo "Promoting deployment with ID: ${{ env.deployment_id }}"
          npx vercel promote ${{ env.deployment_id }} --token=$VERCEL_TOKEN
